<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuackDuck.Application\QuackDuck.Application.csproj" />
    <ProjectReference Include="..\QuackDuck.Infrastructure\QuackDuck.Infrastructure.csproj" />
    <ProjectReference Include="..\QuackDuck.Domain\QuackDuck.Domain.csproj" />
  </ItemGroup>

</Project>
